services:
  s3:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
    volumes:
      - ./aws_scripts:/etc/localstack/init/ready.d
    networks:
      - internal
      - public
  s3_initial_setup:
    image: localstack/localstack
    ports:
      - "4567:6666"
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - SERVICES=s3
      - S3_ENDPOINT_URL=http://s3:4566/
    volumes:
      - ./data/raw:/tmp/localstack
    depends_on:
      - s3
    restart: "no"
    entrypoint: [ "sh", "-c", "sleep 10 && aws --endpoint-url=$$S3_ENDPOINT_URL s3 cp /tmp/localstack/initial_heart_stroke_data.csv s3://heart-stroke-data 
    && aws --endpoint-url=$$S3_ENDPOINT_URL s3 cp /tmp/localstack/heart_stroke_2023-08-08.csv s3://heart-stroke-data" ]
    networks:
      - internal
  mlflow_service:
    image: mlflow_service:v1
    depends_on:
      - s3_initial_setup
    entrypoint: mlflow server --host 0.0.0.0 --port 5000 --default-artifact-root s3://mlflow-artifacts/ --backend-store-uri sqlite:///mlflow.db
    ports:
      - "5000:5000"
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - AWS_DEFAULT_REGION=eu-west-1
      - MLFLOW_S3_ENDPOINT_URL=http://s3:4566
    networks:
      - internal
      - public
  database:
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=prefect
    expose:
      - 5432
    volumes:
      - db:/var/lib/postgresql/data
    networks:
      - internal
      - public
  ### Prefect Server API and UI
  prefect_server:
    image: prefecthq/prefect:2.11.3-python3.9
    restart: always
    #    healthcheck:
    #      test: wget --no-verbose --tries=1 --spider http://prefect_server:4200/api/health || exit 1
    #      interval: 10s
    #      retries: 3
    #      start_period: 20s
    #      timeout: 5s
    volumes:
      - prefect:/root/.prefect
    entrypoint: [ "/opt/prefect/entrypoint.sh","prefect", "server", "start" ]
    environment:
      - PREFECT_UI_URL=http://127.0.0.0:4200/api
      - PREFECT_API_URL=http://127.0.0.1:4200/api
      - PREFECT_SERVER_API_HOST=0.0.0.0
      - PREFECT_API_DATABASE_CONNECTION_URL=postgresql+asyncpg://postgres:postgres@database:5432/prefect
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - AWS_DEFAULT_REGION=eu-west-1
    ports:
      - "4200:4200"
    depends_on:
      - database
    networks:
      - internal
      - public
  ## Prefect Execution Environment
  prefect_execution_environment:
    image: prefect_execution_environment:v1
    restart: always
    entrypoint: [ "/opt/prefect/entrypoint.sh", "prefect", "worker", "start", "-p", "general_worker", "-t", "process" ]
    volumes:
      - ./src:/app/src
    depends_on:
      prefect_server:
        condition: service_started
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - AWS_DEFAULT_REGION=eu-west-1
      - PREFECT_API_URL=http://prefect_server:4200/api
      - MLFLOW_HOST=http://mlflow_service:5000
      - MLFLOW_S3_ENDPOINT_URL=http://s3:4566
      - S3_BUCKET_URL=http://s3:4566/
    networks:
      - internal
  prefect_development_environment:
    image: prefect_development_environment:v1
    depends_on:
      - prefect_server
    volumes:
      - ./src:/app/src
    restart: "no"
    tty: true
    entrypoint: [ "sh", "-c", "sh flows_orchestration_scripts.sh" ]
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - AWS_DEFAULT_REGION=eu-west-1
      - PREFECT_API_URL=http://prefect_server:4200/api
      - MLFLOW_HOST=http://mlflow_service:5000
      - MLFLOW_S3_ENDPOINT_URL=http://s3:4566
      - S3_BUCKET_URL=http://s3:4566/
    networks:
      - internal
      - public
  web_service_prediction:
    restart: always
    image: heart-stroke-prediction-service:v1
    depends_on:
      prefect_development_environment:
        condition:
          service_completed_successfully
      mlflow_service:
        condition:
          service_started
      prefect_execution_environment:
        condition:
          service_started
    ports:
      - "9696:9696"
    environment:
      - AWS_ACCESS_KEY_ID=abc
      - AWS_SECRET_ACCESS_KEY=xyz
      - AWS_DEFAULT_REGION=eu-west-1
      - MLFLOW_HOST=http://mlflow_service:5000
      - MLFLOW_S3_ENDPOINT_URL=http://s3:4566
    networks:
      - internal
      - public
volumes:
  prefect:
  db:
networks:
  internal:
  public:
    driver: bridge