[tool.pylint.messages_control]
disable = [
    "invalid-name",
    "too-many-locals",
    "duplicate-code",
]

[tool.black]
line-length = 88
target-version = ['py39']
skip-string-normalization = true

[tool.isort]
multi_line_output = 3
length_sort = true